/*
 * autogen_TasUpdate_withAerodynamics_alpha_set.c
 *
 * Code generation for function 'autogen_TasUpdate_withAerodynamics_alpha_set'
 *
 * C source code generated on: Wed May 06 13:59:17 2015
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "getAirplane.h"
#include "initStates.h"
#include "magField.h"
#include "propagate.h"
#include "quat2rpy.h"
#include "updateCompass2.h"
#include "updatePosition.h"
#include "updatePressures.h"
#include "updatePressures2.h"
#include "updatePressures_all.h"
#include "updateVelNed.h"
#include "autogen_TasUpdate_withAerodynamics_alpha_set.h"
#include "HyEst_rtwutil.h"

/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */

/* Function Definitions */
void c_autogen_TasUpdate_withAerodyn(const real32_T in1[9], const real32_T in2[7],
  real32_T m, real32_T A, real32_T e[4], real32_T E_z[28], real32_T E_x_dash[36])
{
  real32_T t2;
  real32_T t3;
  real32_T t5;
  real32_T t6;
  real32_T t7;
  real32_T t9;
  real32_T t10;
  real32_T t11;
  real32_T t15;
  real32_T t16;
  real32_T t17;
  real32_T t18;
  real32_T x[28];
  real32_T b_x[36];

  /* AUTOGEN_TASUPDATE_WITHAERODYNAMICS_ALPHA_SET */
  /*     [E,E_Z,E_X_DASH] = AUTOGEN_TASUPDATE_WITHAERODYNAMICS_ALPHA_SET(IN1,IN2,M,A) */
  /*     This function was generated by the Symbolic Math Toolbox version 5.9. */
  /*     06-Jul-2014 12:18:34 */
  t2 = 3.14159274F * in2[6] * 0.00555555569F;
  t3 = 1.0F / in2[3];
  t5 = (real32_T)sqrt(in2[5] * in2[4] * t3 * 574.116F);
  t6 = 1.0F / in2[5];
  t7 = (real32_T)sin(t2);
  t9 = in2[5] * in2[4] * t3;
  t10 = 1.0F / (real32_T)sqrt(t9);
  t11 = (real32_T)cos(t2);
  t2 = rt_powf_snf(in1[1], 2.0F) + rt_powf_snf(in1[3], 2.0F);
  t15 = (real32_T)sqrt(t2);
  e[0] = in1[3] - t5 * t7;
  e[1] = m * (in2[1] - in1[5]) + A * in1[8] * in2[3] * t6 * t15 * in1[2] *
    1.7418083F;
  e[2] = in1[1] - t5 * t11;
  e[3] = in2[3] * 10.0F - in1[7] / rt_powf_snf(t6 * (in2[5] + in1[0] * 0.00649F),
    5.26388407F) * 10.0F;
  t16 = 1.0F / rt_powf_snf(in2[3], 2.0F);
  t17 = (real32_T)sqrt(t9);
  t18 = 1.0F / rt_powf_snf(in2[5], 2.0F);
  t2 = 1.0F / (real32_T)sqrt(t2);
  t5 = in1[0] * t6 * 0.00649F;
  t9 = 1.0F / rt_powf_snf(t5 + 1.0F, 6.26388407F);
  x[0] = 0.0F;
  x[1] = 0.0F;
  x[2] = 0.0F;
  x[3] = 0.0F;
  x[4] = 0.0F;
  x[5] = m;
  x[6] = 0.0F;
  x[7] = 0.0F;
  x[8] = 0.0F;
  x[9] = 0.0F;
  x[10] = 0.0F;
  x[11] = 0.0F;
  x[12] = in2[5] * in2[4] * t7 * 2.5124634E+7F * t10 * t16 * 4.76837158E-7F;
  x[13] = A * in1[8] * t6 * t15 * in1[2] * 1.7418083F;
  x[14] = in2[5] * in2[4] * 2.5124634E+7F * t10 * t11 * t16 * 4.76837158E-7F;
  x[15] = 10.0F;
  x[16] = in2[5] * t3 * t7 * 2.5124634E+7F * t10 * -4.76837158E-7F;
  x[17] = 0.0F;
  x[18] = in2[5] * t3 * 2.5124634E+7F * t10 * t11 * -4.76837158E-7F;
  x[19] = 0.0F;
  x[20] = in2[4] * t3 * t7 * 2.5124634E+7F * t10 * -4.76837158E-7F;
  x[21] = A * in1[8] * in2[3] * t15 * t18 * in1[2] * -1.7418083F;
  x[22] = in2[4] * t3 * 2.5124634E+7F * t10 * t11 * -4.76837158E-7F;
  x[23] = in1[7] * in1[0] * t18 * t9 * -0.341626078F;
  x[24] = 7.8931368E+7F * t11 * t17 * -5.29819077E-9F;
  x[25] = 0.0F;
  x[26] = 3.14159274F * t7 * 2.5124634E+7F * t17 * 5.29819077E-9F;
  x[27] = 0.0F;
  memcpy(&E_z[0], &x[0], 28U * sizeof(real32_T));
  b_x[0] = 0.0F;
  b_x[1] = 0.0F;
  b_x[2] = 0.0F;
  b_x[3] = in1[7] * t6 * t9 * 0.341626078F;
  b_x[4] = 0.0F;
  b_x[5] = A * in1[8] * in2[3] * t6 * t2 * in1[1] * in1[2] * 1.7418083F;
  b_x[6] = 1.0F;
  b_x[7] = 0.0F;
  b_x[8] = 0.0F;
  b_x[9] = A * in1[8] * in2[3] * t6 * t15 * 1.7418083F;
  b_x[10] = 0.0F;
  b_x[11] = 0.0F;
  b_x[12] = 1.0F;
  b_x[13] = A * in1[8] * in2[3] * t6 * t2 * in1[2] * in1[3] * 1.7418083F;
  b_x[14] = 0.0F;
  b_x[15] = 0.0F;
  b_x[16] = 0.0F;
  b_x[17] = 0.0F;
  b_x[18] = 0.0F;
  b_x[19] = 0.0F;
  b_x[20] = 0.0F;
  b_x[21] = -m;
  b_x[22] = 0.0F;
  b_x[23] = 0.0F;
  b_x[24] = 0.0F;
  b_x[25] = 0.0F;
  b_x[26] = 0.0F;
  b_x[27] = 0.0F;
  b_x[28] = 0.0F;
  b_x[29] = 0.0F;
  b_x[30] = 0.0F;
  b_x[31] = 1.0F / rt_powf_snf(t5 + 1.0F, 5.26388407F) * -10.0F;
  b_x[32] = 0.0F;
  b_x[33] = A * in2[3] * t6 * t15 * in1[2] * 1.7418083F;
  b_x[34] = 0.0F;
  b_x[35] = 0.0F;
  memcpy(&E_x_dash[0], &b_x[0], 36U * sizeof(real32_T));
}

/* End of code generation (autogen_TasUpdate_withAerodynamics_alpha_set.c) */
